Repository canonical/istio-operators, pull requests merged in 2023-08, with the labels that each got.

#305 update tox.ini's update-requirements
  charms/istio-gateway/tox.ini
  charms/istio-pilot/tox.ini
  tox.ini
Labels: Libraries: OK

#306 build: bump juju 2.9.44.0, sdi->0.7.0, pyyaml->6.0.1
  .github/workflows/integrate.yaml
  charms/istio-gateway/requirements-unit.txt
  charms/istio-gateway/requirements.txt
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.txt
  requirements-integration.txt
Labels: Libraries: Out of sync

#311 feat: bump istio-operators 1.16->1.17
  charms/istio-gateway/src/manifest.yaml
  charms/istio-gateway/tests/unit/data/egress-example.yaml
  charms/istio-gateway/tests/unit/data/ingress-example.yaml
  charms/istio-pilot/charmcraft.yaml
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/src/manifests/gateway.yaml.j2
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#314 tests: remove wait for idle woraround as juju/python-libjuju#900 is fixed
  tests/test_bundle.py
Labels: Libraries: Out of sync

#312 chore: remove patches for istio < 1.16
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#313 build: unpin setuptools and pip in charmcraft.yaml as pypa/setuptools_scm#713 is fixed
  charms/istio-gateway/charmcraft.yaml
  charms/istio-pilot/charmcraft.yaml
Labels: Libraries: Out of sync

#310 ci: use matrix strategy to test on different microk8s versions
  .github/workflows/integrate.yaml
Labels: Libraries: Out of sync

#291 fix: handle ingress `relation-broken` when `event.app==None`
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: bug, Libraries: Out of sync

#304 Update the bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Libraries: Out of sync

#319 feat: get images on main
  tools/get-images.sh
Labels: Libraries: Out of sync

#323 feat: configurable images for istio-gateway
  charms/istio-gateway/config.yaml
  charms/istio-gateway/src/charm.py
  charms/istio-gateway/src/manifest.yaml
Labels: Libraries: Out of sync
