Repository canonical/istio-operators, pull requests merged in 2023-03, with the labels that each got.

#184 bump all charm libs to latest version
  charms/istio-pilot/lib/charms/grafana_k8s/v0/grafana_dashboard.py
  charms/istio-pilot/lib/charms/observability_libs/v0/juju_topology.py
  charms/istio-pilot/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Labels: Libraries: OK

#201 ci: bump juju agent 2.9.34 -> 2.9.42 (#200)
  .github/workflows/integrate.yaml
  tests/test_bundle.py
  tests/test_cos_integration.py
Labels: Libraries: Out of sync

#191 feat: istioctl wrapper
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.in
  charms/istio-pilot/requirements.txt
  charms/istio-pilot/src/istioctl.py
  charms/istio-pilot/tests/unit/conftest.py
  charms/istio-pilot/tests/unit/data/istioctl_version_output_no_pilot_in_control.yaml
  charms/istio-pilot/tests/unit/data/istioctl_version_output_template.yaml.j2
  charms/istio-pilot/tests/unit/data/istioctl_version_output_template_no_control.yaml.j2
  charms/istio-pilot/tests/unit/data/istioctl_version_output_too_many_meshes.yaml
  charms/istio-pilot/tests/unit/example_manifest.yaml
  charms/istio-pilot/tests/unit/test_charm.py
  charms/istio-pilot/tests/unit/test_istioctl.py
Labels: enhancement, Libraries: Out of sync

#198 feat: Add upgrade handling to istio-pilot
  charms/istio-gateway/requirements-fmt.txt
  charms/istio-gateway/requirements-lint.in
  charms/istio-gateway/requirements-lint.txt
  charms/istio-gateway/requirements-unit.txt
  charms/istio-gateway/requirements.in
  charms/istio-gateway/requirements.txt
  charms/istio-gateway/tox.ini
  charms/istio-pilot/README.md
  charms/istio-pilot/requirements-fmt.txt
  charms/istio-pilot/requirements-lint.in
  charms/istio-pilot/requirements-lint.txt
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.in
  charms/istio-pilot/requirements.txt
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  charms/istio-pilot/tox.ini
  requirements-fmt.txt
  requirements-integration.txt
  requirements-lint.txt
  tox.ini
Labels: enhancement, Libraries: Out of sync

#206 docs: add detail to istio-pilot upgrade recovery instructions
  charms/istio-pilot/README.md
Labels: documentation, Libraries: Out of sync

#214 fix: add missing volume mounts and volumes to istio-gateway's gateway
  charms/istio-gateway/src/manifest.yaml
  charms/istio-gateway/tests/unit/data/egress-example.yaml
  charms/istio-gateway/tests/unit/data/ingress-example.yaml
Labels: Libraries: Out of sync

#210 fix: patches misconfigured ValidatingWebhook on Install
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#216 backport bug fixes to `track/1.16`
  charms/istio-gateway/src/manifest.yaml
  charms/istio-gateway/tests/unit/data/egress-example.yaml
  charms/istio-gateway/tests/unit/data/ingress-example.yaml
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#220 feat: make upgrade_charm handler wait on Istio's deployment during upgrades
  charms/istio-pilot/README.md
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.in
  charms/istio-pilot/requirements.txt
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#221 doc: update istio-pilot readme.md
  charms/istio-pilot/README.md
Labels: Libraries: Out of sync

#226 backport: upgrade_charm handler fixes from #220 to `track/1.13`
  charms/istio-pilot/README.md
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.in
  charms/istio-pilot/requirements.txt
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#225 backport: upgrade_charm handler fixes from #220 to `track/1.14`
  charms/istio-pilot/README.md
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.in
  charms/istio-pilot/requirements.txt
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#224 backport: upgrade_charm handler fixes from #220 to `track/1.15`
  charms/istio-pilot/README.md
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.in
  charms/istio-pilot/requirements.txt
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#223 backport: upgrade_charm handler fixes from #220 to `track/1.16`
  charms/istio-pilot/README.md
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.in
  charms/istio-pilot/requirements.txt
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#222 backport: upgrade_charm handler fixes from #220 to `track/1.12`
  charms/istio-pilot/README.md
  charms/istio-pilot/requirements-unit.txt
  charms/istio-pilot/requirements.in
  charms/istio-pilot/requirements.txt
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
Labels: Libraries: Out of sync
