Repository canonical/istio-operators, pull requests merged in 2024-09, with the labels that each got.

#542 Fix tag istio-pilot dashboard tag
  charms/istio-pilot/src/grafana_dashboards/istio_control_plane.json.tmpl
Labels: bug, Libraries: Out of sync

#548 chore(backport-1.17): Pin charmcraft channel to `3.x/stable`
  .github/workflows/integrate.yaml
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#547 chore(backport-1.18): Pin charmcraft channel to `3.x/stable`
  .github/workflows/integrate.yaml
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#546 chore(backport-1.19): Pin charmcraft channel to `3.x/stable`
  .github/workflows/integrate.yaml
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#544 chore(backport-1.21): Pin charmcraft channel to `3.x/stable`
  .github/workflows/integrate.yaml
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#543 chore(backport-1.22): Pin charmcraft channel to `3.x/stable`
  .github/workflows/integrate.yaml
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#550 chore(backport): Fix tag istio-pilot dashboard tag (#542)
  charms/istio-pilot/src/grafana_dashboards/istio_control_plane.json.tmpl
Labels: Libraries: Out of sync

#554 Feat: Add Terraform modules
  .github/workflows/integrate.yaml
  .gitignore
  charms/istio-gateway/terraform/README.md
  charms/istio-gateway/terraform/main.tf
  charms/istio-gateway/terraform/outputs.tf
  charms/istio-gateway/terraform/variables.tf
  charms/istio-gateway/terraform/versions.tf
  charms/istio-gateway/tox.ini
  charms/istio-pilot/terraform/README.md
  charms/istio-pilot/terraform/main.tf
  charms/istio-pilot/terraform/outputs.tf
  charms/istio-pilot/terraform/variables.tf
  charms/istio-pilot/terraform/versions.tf
  charms/istio-pilot/tox.ini
Labels: Libraries: OK

#555 (backport) Feat: Create Terraform module
  .github/workflows/integrate.yaml
  .gitignore
  charms/istio-gateway/terraform/README.md
  charms/istio-gateway/terraform/main.tf
  charms/istio-gateway/terraform/outputs.tf
  charms/istio-gateway/terraform/variables.tf
  charms/istio-gateway/terraform/versions.tf
  charms/istio-gateway/tox.ini
  charms/istio-pilot/terraform/README.md
  charms/istio-pilot/terraform/main.tf
  charms/istio-pilot/terraform/outputs.tf
  charms/istio-pilot/terraform/variables.tf
  charms/istio-pilot/terraform/versions.tf
  charms/istio-pilot/tox.ini
Labels: Libraries: Out of sync
