Repository canonical/istio-operators, pull requests merged in 2024-08, with the labels that each got.

#477 Add metrics-endpoint to istio-gateway
  charms/istio-gateway/charmcraft.yaml
  charms/istio-gateway/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  charms/istio-gateway/metadata.yaml
  charms/istio-gateway/requirements-unit.txt
  charms/istio-gateway/requirements.in
  charms/istio-gateway/requirements.txt
  charms/istio-gateway/src/charm.py
  charms/istio-gateway/src/manifest.yaml
  charms/istio-gateway/src/prometheus_alert_rules/basic.rules
  charms/istio-gateway/src/prometheus_alert_rules/workload.rules
  charms/istio-gateway/tests/unit/data/egress-example.yaml
  charms/istio-gateway/tests/unit/data/ingress-example.yaml
  charms/istio-gateway/tests/unit/test_charm.py
  requirements-integration.in
  requirements-integration.txt
  requirements-lint.in
  requirements-lint.txt
  tests/test_bundle.py
  tests/test_cos_integration.py
  tox.ini
Labels: enhancement, Libraries: Out of sync

#494 tests: remove public-url config and add dex-oidc-config relation
  tests/test_bundle.py
Labels: Libraries: Out of sync

#492 tests: remove public-url config and add dex-oidc-config relation
  tests/test_bundle.py
Labels: Libraries: Out of sync

#491 tests: remove public-url config and add dex-oidc-config relation
  tests/test_bundle.py
Labels: Libraries: Out of sync

#495 ci(upload-charm): use charmcraft from latest/candidate
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#500 ci(upload-charm): use charmcraft from latest/candidate in track/1.19
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#501 ci(upload-charm): use charmcraft from latest/candidate in track/1.20
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#503 ci(upload-charm): use charmcraft from latest/candidate in track/1.22
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#490 tests: remove public-url config and add dex-oidc-config relation
  tests/test_bundle.py
Labels: Libraries: Out of sync

#499 ci(upload-charm): use charmcraft from latest/candidate in track/1.18
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#517 chore(lib): Update cert_handler library to v1
  charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
  charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
  charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  tests/test_bundle.py
  tests/test_cos_integration.py
Labels: bug, Libraries: Out of sync

#520 Update cert_handler lib
  .github/workflows/integrate.yaml
  charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
  charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
  charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  tests/test_bundle.py
  tests/test_cos_integration.py
Labels: bug, Libraries: OK

#514 Add alert rules to istio-gateway based on the KF093 spec
  charms/istio-gateway/src/prometheus_alert_rules/KubeflowIstioGatewayServices.rules
Labels: Libraries: Out of sync

#515 Add alert rules to istio-pilot based on the KF093 spec
  charms/istio-pilot/src/prometheus_alert_rules/KubeflowIstioPilotServices.rules
Labels: Libraries: OK

#521 chore(backport): Bacport changes from dev branch #520
  .github/workflows/integrate.yaml
  charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
  charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
  charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  tests/test_bundle.py
Labels: bug, Libraries: Out of sync

#523 chore(backport-1.20): Bacport changes from dev branch #520
  .github/workflows/integrate.yaml
  charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
  charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
  charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  tests/test_bundle.py
Labels: bug, Libraries: Out of sync

#522 chore(backport-1.19): Bacport changes from dev branch #520
  .github/workflows/integrate.yaml
  charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
  charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
  charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  tests/test_bundle.py
Labels: bug, Libraries: Out of sync

#512 fix(ci): use charmcraft from latest/candidate in integration tests
  .github/workflows/integrate.yaml
Labels: Libraries: Out of sync

#529 chore(backport-1.17): Backport changes from dev branch #520
  .github/workflows/integrate.yaml
  charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
  charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
  charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  tests/test_bundle.py
Labels: Libraries: Out of sync

#524 chore(backport-1.21): Bacport changes from dev branch #520
  .github/workflows/integrate.yaml
  charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
  charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
  charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  tests/test_bundle.py
Labels: bug, Libraries: Out of sync

#525 chore(backport-1.22): Bacport changes from dev branch #520
  .github/workflows/integrate.yaml
  charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
  charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
  charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  charms/istio-pilot/src/charm.py
  charms/istio-pilot/tests/unit/test_charm.py
  tests/test_bundle.py
Labels: bug, Libraries: Out of sync

#498 ci(upload-charm): use charmcraft from latest/candidate in track/1.17
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#502 ci(upload-charm): use charmcraft from latest/candidate in track/1.21
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#478 Add istio control plane dashboard and alert rule
  charms/istio-gateway/src/prometheus_alert_rules/basic.rules
  charms/istio-pilot/src/grafana_dashboards/istio_control_plane.json.tmpl
  charms/istio-pilot/src/prometheus_alert_rules/IstioPilotDuplicateEntry.rule
  tests/test_cos_integration.py
Labels: enhancement, Libraries: Out of sync

#537 chore(backport): Backport metrics work (KF-5558) to track/1.22
  charms/istio-gateway/charmcraft.yaml
  charms/istio-gateway/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  charms/istio-gateway/metadata.yaml
  charms/istio-gateway/requirements-unit.txt
  charms/istio-gateway/requirements.in
  charms/istio-gateway/requirements.txt
  charms/istio-gateway/src/charm.py
  charms/istio-gateway/src/manifest.yaml
  charms/istio-gateway/src/prometheus_alert_rules/KubeflowIstioGatewayServices.rules
  charms/istio-gateway/src/prometheus_alert_rules/basic.rules
  charms/istio-gateway/src/prometheus_alert_rules/workload.rules
  charms/istio-gateway/tests/unit/data/egress-example.yaml
  charms/istio-gateway/tests/unit/data/ingress-example.yaml
  charms/istio-gateway/tests/unit/test_charm.py
  charms/istio-pilot/src/grafana_dashboards/istio_control_plane.json.tmpl
  charms/istio-pilot/src/prometheus_alert_rules/IstioPilotDuplicateEntry.rule
  charms/istio-pilot/src/prometheus_alert_rules/KubeflowIstioPilotServices.rules
  requirements-integration.in
  requirements-integration.txt
  requirements-lint.in
  requirements-lint.txt
  tests/test_cos_integration.py
  tox.ini
Labels: enhancement, Libraries: OK
